#The default YAML file in development
#version: "3.9"

services:

  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis_data_dev
    environment:
      POSTGRES_DB: sleepdb
      POSTGRES_USER: sleepuser
      POSTGRES_PASSWORD: sleeppassword
    ports:
      - "5433:5432" #different exposed port as production: 5433
    volumes:
      - postgis_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  flask_api:
    build: .
    container_name: flask_api
    volumes:
      - ./app:/app  # This is fine now because the script is NOT in /app
    depends_on:
      - redis
      - postgis
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://sleepuser:sleeppassword@postgis:5432/sleepdb
      # No command needed - using CMD from Dockerfile

  celery_worker:
    build: .
    container_name: celery_worker
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - postgis
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://sleepuser:sleeppassword@postgis:5432/sleepdb
    command: celery -A tasks.celery_app worker --loglevel=info --concurrency=5

volumes:
  postgis_data_dev:
